language: rust
cache: cargo

before_script:
  - rustup component add rustfmt || true
  - rustup component add clippy || true

matrix:
  include:
    - rust: 1.34.2
      env: ALL_FEATURES='std,serde'
    - rust: stable
      env: ALL_FEATURES='std,serde'
    - rust: beta
      env: ALL_FEATURES='std,serde'
    - rust: nightly
      env: ALL_FEATURES='std,serde,rocket'
  allow_failure:
    - rust: nightly

script:
  - ( rustup component list | grep -q clippy ) &&
      cargo fmt --all -- --check
  - ( rustup component list | grep -q rustfmt ) &&
      cargo clippy --all --all-targets --features "$ALL_FEATURES" -- -D warnings
  # Almost all tests without std / no_std mode
  - cargo test --all --no-default-features --verbose
  # Almost all tests with std features enabled
  - cargo test --all --features "$ALL_FEATURES" --verbose
  # Remaining tests (that require `cfg(not(debug_assertions))`)
  - cargo test --release --verbose

notifications:
  email:
    on_success: never
