language: rust
cache: cargo

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-targets --all-features -- -D warnings
  # Almost all tests without std / no_std mode
  - cargo test --all --no-default-features --verbose
  # Almost all tests with std features enabled
  - if [ "$TRAVIS_RUST_VERSION" = 'nightly' ]; then
      cargo test --all --all-features --verbose
    else
      cargo test --all --features std,serde --verbose
    fi
  # Remaining tests (that require `cfg(not(debug_assertions))`)
  - cargo test --release --verbose

notifications:
  email:
    on_success: never
