[package]
name = "js_int"
description = "JavaScript-interoperable integer types"
version = "0.1.1"
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/jplatte/js_int.git"
keywords = ["integer", "no_std"]
categories = ["no-std"]

[dependencies.serde]
version = "1.0"
optional = true
default-features = false
features = ["derive"]

[features]
default = ["std"]
std = []

[badges.travis-ci]
repository = "jplatte/js_int"
branch = "master"

[workspace]
members = ["ext_tests"]
