[package]
name = "js_int"
version = "0.1.0"
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
edition = "2018"

[dependencies.serde]
version = "1.0"
optional = true
default-features = false
features = ["derive"]

[features]
default = ["std"]
std = []

[workspace]
members = ["ext_tests"]
